name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Clean install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test
    - name: Install VS Code Extension Manager
      run: npm i -g vsce
    - name: Publish extension
      run: vsce publish -p ${{secrets.VSCE_PAT}}
